# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

      
build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, nitish-mac-runner]
      

    #nitish-mac-runne
    #runs-on: nitish-mac-runner
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    #jobs:
 
       # env :
        #  MAVEN_PATH: '/Users/nitishkumar/Desktop/jenkins/maven/apache-maven-3.8.1'
   
      # Runs a single command using the runners shell
      - name: Run a maven build
        run: |
           export PATH=/Users/nitishkumar/Desktop/jenkins/maven/apache-maven-3.8.1/bin:$PATH,
           mvn package && 
           echo $(pwd)
           
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo "test"
 
  Deploy:
    needs: build
    runs-on: [self-hosted, nitish-mac-runner]
    steps:
      - run: echo "deployed"

          
